# Codecov configuration for coverage tracking and reporting
# Reference: https://docs.codecov.com/docs/codecov-yaml

coverage:
  precision: 2
  round: down
  range: "70...100"
  status:
    project:
      default:
        target: 80
        threshold: 5
        base: auto
    patch:
      default:
        target: 80
        threshold: 5
    changes:
      default:
        target: 80
        threshold: 5

flags:
  unittests:
    carryforward: true
    paths:
      - src
      - api
      - tests

comment:
  layout: "reach,diff,flags,tree,files"
  behavior: default
  require_changes: false
  require_base: false
  require_head: yes
  after: "footer"

# Ignore certain file paths from coverage
ignore:
  - "node_modules"
  - "tests"
  - "dist"
  - "**/*.test.ts"
  - "**/*.test.tsx"
  - "**/index.ts"
  - "src/main.tsx"
  - "src/types/index.ts"

# Define coverage thresholds
coverage_error_threshold: 80
coverage_precision: 2

# Parsers configuration
parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      partial_line: no

# Compare coverage with main branch
compare:
  branch: main
